

AdminUsers =  module.exports ={
	"charlie@playcrab.com":{name:"吴磊"},
	"chengchen@playcrab.com":{name:"程晨"},
	"chenhk@playcrab.com":{name:"谌红坤"},
	"clara@playcrab.com":{name:"高虹"},
	"didiv@playcrab.com":{name:"杜杨"},
	"hi@playcrab.com":{name:"Hi"},
	"hr@playcrab.com":{name:"HR"},
	"james@playcrab.com":{name:"施展"},
	"jettie@playcrab.com":{name:"于杰"},
	"kevin@playcrab.com":{name:"叶凯"},
	"kf.wuxia@playcrab.com":{name:"武侠客服"},
	"leiolio@playcrab.com":{name:"王晓东"},
	"linying@playcrab.com":{name:"林影"},
	"liuyang@playcrab.com":{name:"刘洋"},
	"liwh@playcrab.com":{name:"李旺洪"},
	"maoxian@playcrab.com":{name:"冒险客服"},
	"monitor@playcrab.com":{name:"monitor"},
	"owen@playcrab.com":{name:"欧阳刘彬"},
	"qianzixun110@playcrab.com":{name:"樊丽娜"},
	"quning@playcrab.com":{name:"曲宁"},
	"redmine@playcrab.com":{name:"redmine"},
	"srgzyq@playcrab.com":{name:"石锐"},
	"tingkun@playcrab.com":{name:"曾廷坤"},
	"wancheng@playcrab.com":{name:"胡磊万城"},
	"wangkun@playcrab.com":{name:"王定坤"},
	"weiy@playcrab.com":{name:"杨薇"},
	"wely@playcrab.com":{name:"尹力炜"},
	"yangcl@playcrab.com":{name:"杨成龙"},
	"yewei@playcrab.com":{name:"叶伟"},
	"design@playcrab.com":{name:"策划"},
	"dev@playcrab.com":{name:"攻城师"},
	"livemall@playcrab.com":{name:"购物天堂"},
	"livemall_report@playcrab.com":{name:"购物天堂 数据"},
	"kf@playcrab.com":{name:"客服"},
	"art@playcrab.com":{name:"美术"},
	"prisonville@playcrab.com":{name:"prisonville"},
	"all@playcrab.com":{name:"所有人"},
	"zeus@playcrab.com":{name:"我的冒险"},
	"adventure_report@playcrab.com":{name:"我的冒险 数据"},
	"wuxia@playcrab.com":{name:"武侠项目"},
	"op@playcrab.com":{name:"运营组"}
}
